//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyBook.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TID { get; set; }
        public System.DateTime Date { get; set; }
        public string Payee { get; set; }
        public string Memo { get; set; }
        public int CTID { get; set; }
        public string CheckNum { get; set; }
        public decimal Amount { get; set; }
        public int AID { get; set; }
        public int STID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual StateType StateType { get; set; }
    }
}
